apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-nginx
  namespace: default
  labels:
    app: nginx
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      version: green
  template:
    metadata:
      labels:
        app: nginx
        version: green
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
