apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default  # Specify your namespace here
spec:
  selector:
    app: nginx
    version: green  # Initially, this will point to the Blue version
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
